config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/secret'
  root to: "event#index"

  resources :event
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event
  validates :stripe_customer_id, presence: true
  after_create :attendance_send
  
  def attendance_send
    UserMailer.attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  validates :start_date, presence: true
  validate :start_date_after_date
  validates :duration, numericality: { only_integer: true }
  validate :ismultiple_of_5?
  validates :title, presence: true, length: {in: 5..140}
  validates :description, presence: true, length: {in: 20..1000}
  validates :price, :inclusion => 1..1000
  validates :location, presence: true

  
  private
  
  def start_date_after_date
    date=Time.now
    return if date.blank? || start_date.blank?

    if date > start_date
      errors.add(:date, "must be after the date")
    end
 end

 def ismultiple_of_5?
  return if duration.blank?

  if duration%5 !=0 || duration < 0
    errors.add(:duration, "must be a positive number multiple of 5")
  end
end

end

app/models/test.rb
class Test < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :attendances
  has_many :events, through: :attendances
    after_create :welcome_send
  
    def welcome_send
      UserMailer.welcome_email(self).deliver_now
      puts "#"*100
      puts "Welcome email"
      puts "#"*100
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  def index
    @events = Event.all
  end
  def show
    @event = params[:id]
  end
  def new
  end


  def create


    @event = Event.create(title: params[:event_title], description: params[:event_description], start_date: params[:event_start_date],duration: params[:event_duration],price: params[:event_price],location: params[:event_location], user_id: current_user.id)
    puts "#"*100
    puts @event.errors
    puts "#"*100
    
    if @event.save # essaie de sauvegarder en base @gossip
      # si ça marche, il redirige vers la page d'index du site
      # flash[:notice] = "Post successfully created"
      # gflash :success => "The product has been created successfully!"
      flash["success"] = "event successfully created!"
      redirect_to event_index_path
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      flash["error"] = "event don't created"
      render new_event_path
    end
  end


  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]

  def index
    @user= User.find_by(id: current_user)
  end

  def secret
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
       user=User.create(first_name: Time.now.to_i.to_s, email: "matthieubacheley@gmail.com")
      puts "#"*100
      puts user.errors
      puts "#"*100
      #  UserMailer.welcome_email(user).deliver_now
      #  UserMailer.attendance_email(user).deliver_now
       
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create]
  before_action :authenticate_user!, only: [:index, :show]

  def new
    @user = User.new
  end

  # def create
  #   @user = User.create(params.require(:user).permit(:email, :password, :first_name, :last_name, :city_id, :remember_check))
  #   if @user.remember_check
  #     remember(@user)
  #   end
  #   session[:user_id] = @user.id
  #   redirect_to gossips_path
  # end

  def show
    @user = params[:id]
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-danger"
    end
  end
  
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/event/index.html.erb
<% @events.each do |event| %>
<div class="list-group">

  <a href="<%= event_path(event.id) %>" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">title : <%= event.title %></h5>
      
      <small class="text-muted"><%= event.updated_at %></small>
    </div>
    

    <p class="mb-1">description : <%= event.description %></p>
    <p class="mb-1">price : <%= event.price %></p>
    <p class="mb-1">location : <%= event.location %></p>
    <p class="mb-1">duration : <%= event.duration %></p>
    <p class="mb-1">start_date : <%= event.start_date %></p>
    </a>
<% attendances_count= Attendance.all.count %> 
<a href="/event/<%= event.id %>" class="list-group-item list-group-item-action"> Participants : <%= attendances_count%></a>
</div>
<br/>
<%end%>

app/views/event/new.html copy.erb
<form action= <%= event_index_path %> method="POST">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
  <p>Event Title : </p>
  <input type="text" name="event_title"><br/>
  <p>Event Description : </p>
  <input type="text" name="event_description"><br/>
    <p>Event Start Date : </p>
  <input type="text" name="event_start_date"><br/>
    <p>Event Duration : </p>
  <input type="text" name="event_duration"><br/>
    <p>Event Price : </p>
  <input type="text" name="event_price"><br/>
    <p>Event Location : </p>
  <input type="text" name="event_location"><br/>
  <input type="submit" value="create event"><br/>
</form>



<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for("event", :url => new_event_path, html: { method: :post }) do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Create a new Event</h1>

        <div class="form-group">
          <%= f.label :event_title %><br />
          <%= f.text_field :title, autofocus: true,  class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :event_description %><br />
          <%= f.text_field :description, autofocus: true,  class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :event_start_date %><br />
          <%= f.text_field :start_date, autofocus: true,  class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :event_duration %><br />
          <%= f.text_field :duration, autofocus: true,  class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :event_price %><br />
          <%= f.text_field :price, autofocus: true,  class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :event_location %><br />
          <%= f.text_field :location, autofocus: true,  class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit "create event", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>


    </div>
  </div>
</div>


event = Event.create(title: params[:event_title], description: params[:event_description], start_date: params[:event_start_date],duration: params[:event_duration],price: params[:event_price],location: params[:event_location], user_id: current_user.id)

app/views/event/new.html.erb
<form action= <%= event_index_path %> method="POST">
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
  <p>Event Title (min 6): </p>
  <input type="text" name="event_title"><br/>
  <p>Event Description (min 20): </p>
  <input type="text" name="event_description"><br/>
    <p>Event Start Date (futur only): </p>
  <input type="text" name="event_start_date"><br/>
    <p>Event Duration (int multiple of 5): </p>
  <input type="text" name="event_duration"><br/>
    <p>Event Price (int): </p>
  <input type="text" name="event_price"><br/>
    <p>Event Location (presence): </p>
  <input type="text" name="event_location"><br/>
  <input type="submit" value="create event"><br/>
</form>

app/views/event/show.html.erb
<% @event = Event.find_by(id: @event) %>
<% @user = User.find_by(id: @event.user_id) %>
start_date:<%= @event.start_date %><br />
duration:<%= @event.duration %><br />
title:<%= @event.title %><br />
description:<%= @event.description %><br />
price:<%= @event.price %><br />
location:<%= @event.location %><br />
created_at:<%= @event.created_at %><br />
updated_at:<%= @event.updated_at %><br />
participants: <%= @attendances_count %><br />
admin user: <%= @user.email %><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>My New Event Brite Like App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <div class="container-flex">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">My New Event Brite Like App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=<%= new_event_path%>>new event</a>
      </li>
        </div>


        <% if user_signed_in? %>

        <a class="nav-link"> <%= button_to "User : #{current_user.email}", edit_user_registration_path, method: :get %> </a>
 

        <a class="nav-link"> <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete %></a>

<% else %>

        <%= button_to "Login", new_user_session_path, method: :get%>
      
   
        <%= button_to "Sign Up", new_user_registration_path, method: :get%>



<%end%>
</nav>
</div>
</div>
<% flash.each do |key, value| %>
<div id="close" class="<%= flash_class(key) %>" role="alert">
  <%= value %>
</div>
<% end %>

  </head>

  <body>
    <%= yield %>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/index.html.erb
<% @users.order(:first_name).each do |user| %>
<div class="card" >
  <div class="card-body">
    User : <a class="card-link"><%= link_to "#{user.first_name} #{user.last_name}",user_path(user.id) %></a><br/>
    Descripton : <%= user.description%><br/>
    E-mail : <%= user.email%><br/>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%> 
<%= f.label :first_name%><br> 
<%= f.text_field :first_name%><br> 
<%= f.label :last_name%><br> 
<%= f.text_field :last_name%><br> 
<%= f.label :email%><br> 
<%= f.text_field :email%><br> 
<%= f.label :password%><br> 
<%= f.password_field :password%><br> 
<%= f.label :city_id%><br> 
<%sample_city=City.all.sample%>
<%= f.text_field :city_id, value: sample_city.id%>  <%=sample_city.name%> <br> 
<%= f.label :remember_check%><br> 
<%= f.check_box :remember_check,{:checked=>true}%><br> 
<%= f.submit %>

<%end%>

app/views/users/show.html.erb
<% @user = User.find_by(id: @user) %>
<div class="card" >
  <div class="card-body">
    <h5 class="card-title">First and Last Name : <%= @user.first_name %> <%= @user.last_name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Email : <%= @user.email %></h6>
    <p class="card-text">Description : <%= @user.description %></p>
    
  </div>
</div>